services:
  backend:
    build: ./server
    volumes:
      - ./server:/app/server
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    command: python3 run.py
    depends_on:
      - db
    links:
      - db
  frontend:
    build: ./ktdash_frontend
    volumes:
      - ./ktdash_frontend:/app
      # One-way volume to use node_modules from inside image
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    command: npm start
  db:
    image: mysql:8.0
    restart: always
    container_name: ktdash_database
    ports:
     - "3306:3306"
    expose:
      - "3306"
    volumes:
      - "./server/db/schema.sql:/docker-entrypoint-initdb.d/1.sql"
    environment:
      - MYSQL_ROOT_PASSWORD=superSecretPassword
      - MYSQL_DATABASE=killteam
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
volumes:
  db:
    driver: local