services:
  backend:
    build: ./server
    volumes:
      - ./server:/app/server
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    command: python3 run.py
  frontend:
    build: ./ktdash_frontend
    volumes:
      - ./ktdash_frontend:/app
      # One-way volume to use node_modules from inside image
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    command: npm start